In [1]:
import numpy as np
import pandas as pd

In [2]:
train = r"D:\LULC\raw_data\0_groundtruth\SACLAJ_2014_2016_catclearned.csv"
train = r"D:\LULC\raw_data\0_groundtruth\SACLAJ-master.csv"
df_train = pd.read_csv(train)
df_train

C:\Users\GE\Anaconda3\envs\LULC\lib\site-packages\IPython\core\interactiveshell.py:3147: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,photo_date,file_name,category_master,category,category_details,diameter,target_lat,target_lon,photographer_lat,photographer_lon,sgli_lat,sgli_lon,note,created_at,updated_at,nickname,Unnamed: 17
0,1,2014:04:14 15:06:48,2014_0414_1506_N35E139_cimg3174.jpg,JAXA_LULC,dbf,NaN,100,35.560440,139.212692,35.563698,139.205652,NaN,NaN,NaN,2014/8/8 2:26,2016/12/8 6:37,Kenlo Nasahara,NaN
1,2,2013:12:02 15:11:33,20131202miyakojima_2.JPG,JAXA_LULC,other crop,NaN,30,24.824808,125.318985,24.824607,125.318993,NaN,NaN,NaN,2014/8/8 2:26,2016/12/8 6:36,anonymous53,NaN
2,3,2013:10:17 12:47:35,20131017watari_13.JPG,JAXA_LULC,rice,rice paddy,80,38.062115,140.890457,38.062573,140.889882,NaN,NaN,NaN,2014/8/8 2:27,2016/12/8 6:36,anonymous53,NaN
3,4,2013:10:17 13:13:10,20131017watari_11.JPG,JAXA_LULC,rice,rice paddy,40,38.062504,140.881317,38.061897,140.881142,NaN,NaN,NaN,2014/8/8 2:27,2016/12/8 6:36,anonymous53,NaN
4,5,2013:10:17 13:23:22,20131017watari_12.JPG,JAXA_LULC,other crop,soybean,30,38.062672,140.882278,38.062672,140.882068,NaN,NaN,NaN,2014/8/8 2:27,2016/7/21 6:09,anonymous53,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62254,62348,2080:01:09 01:53:20,CIMG9611.JPG,JAXA_LULC,grasslands,NaN,30,47.778181,106.743815,47.777925,106.742672,NaN,NaN,NaN,25:25.7,25:25.7,undrakh,NaN
62255,62349,2080:01:09 01:53:13,CIMG9610.JPG,JAXA_LULC,grasslands,NaN,30,47.778165,106.743982,47.777925,106.742672,NaN,NaN,NaN,25:32.5,25:32.5,undrakh,NaN
62256,62350,2080:01:09 01:53:08,CIMG9609.JPG,JAXA_LULC,grasslands,NaN,30,47.778277,106.744125,47.777925,106.742672,NaN,NaN,NaN,25:38.4,25:38.4,undrakh,NaN
62257,62351,2080:01:05 23:59:46,CIMG9608.JPG,JAXA_LULC,grasslands,NaN,30,47.778133,106.744244,47.777925,106.742672,NaN,NaN,NaN,25:44.1,25:44.1,undrakh,NaN
62258,62352,2080:01:05 23:59:57,CIMG9999.JPG,JAXA_LULC,grasslands,NaN,30,45.854127,106.334897,45.854032,106.334585,NaN,NaN,NaN,20:18.3,20:18.3,undrakh,NaN

In [3]:
unique = np.unique(df_train["category"])
unique

array(['aquaculture', 'bamboo', 'barren', 'broadleaf forests',
       'closed shrublands', 'croplands', 'dbf', 'dbf/plantation',
       'deciduous forests', 'dnf', 'ebf', 'ebf/plantation', 'enf',
       'evergreen forests', 'forest', 'grasslands', 'herbs', 'lands',
       'mixed forests', 'needleleaf forests', 'non-vegetation',
       'open shrublands', 'orchard', 'other crop', 'pasture', 'rice',
       'savannas', 'shrublands', 'snow and ice', 'urban and built-up',
       'vegetation', 'water area', 'wetlands', 'wood lands'], dtype=object)

In [5]:
len(unique)

34

In [7]:
hand_unique = ['Water', 'Urban and built-up', 'Rice paddy', 'Crops', 'Grassland', 'DBF', 'DNF', 'EBF', 'ENF', 'Bare land']
for i in hand_unique:
    num = sum(df_train["category"]==i)
    print(f"{i} = {num}å€‹")

Water = 1714å€‹
Urban and built-up = 3500å€‹
Rice paddy = 8775å€‹
Crops = 6313å€‹
Grassland = 3807å€‹
DBF = 3246å€‹
DNF = 438å€‹
EBF = 1242å€‹
ENF = 4176å€‹
Bare land = 877å€‹

In [6]:
df_train["category"].describe()

count          34088
unique            10
top       Rice paddy
freq            8775
Name: category, dtype: object